// @flow

export const API_PENDING = "FINISH_DELIVERIES_API_PENDING";
export const API_SUCCESS = "FINISH_DELIVERIES_API_SUCCESS";
export const API_ERROR = "FINISH_DELIVERIES_API_ERROR";
export const API_DELETE = "FINISH_DELIVERIES_API_DELETE";
export const API_UPDATE = "FINISH_DELIVERIES_API_UPDATE";
export const API_ADD = "FINISH_DELIVERIES_API_ADD";
